name: Check Wlodzimiers Blocks
on:
  - push
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Fetch Tags
        run: git fetch --unshallow --tags -f
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.11.1
      - name: Check Build
        run: ./gradlew check